version: '3.8'
services:
  storybook:
    build: .
    ports:
      - "6006:6006"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run storybook -- --no-open
